### ISSUE TITLE
設定画面の表示が崩れる

### ISSUE THREAD

**Issue by ghost** [watasuke102/ExpNote#1]
![Screenshot_20201022_184924_com example ExpNote](https://user-images.githubusercontent.com/61766302/96855236-69a57380-1497-11eb-9822-0aa9e7085c31.jpg)
正しいものを見ていないのでどういう状況か分かりませんが、おそらく設定画面の表示が崩れていると思われます。
Huawei p20 lite、EMUIバージョンが9.1.0です。解像度が2280x1080です。

**Comment by watasuke102** [comment]
2.0.1で修正されています
